#ifndef CHANNEL_HIJACK_GFX_INDICES_H
#define CHANNEL_HIJACK_GFX_INDICES_H

typedef enum {
  GFX_MODEL_BUG_SHIP = 0,
  GFX_MODEL_SPHERE = 1,
  GFX_MODEL_MAGGOT = 2,
  GFX_MODEL_SATELLITE = 3,
  GFX_MODEL_BEETLE1 = 4,
  GFX_MODEL_BEETLE2 = 5,
  GFX_MODEL_BEETLE3 = 6,
  GFX_MODEL_BIG_BEETLE_PART1 = 7,
  GFX_MODEL_BIG_BEETLE_PART2 = 8,
  GFX_MODEL_BIG_BEETLE_PART3 = 9,
  GFX_MODEL_BIG_BEETLE_PART4 = 10,
  GFX_MODEL_BIG_BEETLE_PART5 = 11,
  GFX_MODEL_BIG_BEETLE_PART6 = 12,
  GFX_MODEL_BIG_BEETLE_PART7 = 13,
  GFX_MODEL_BIG_BEETLE_PART8 = 14,
  GFX_MODEL_BIG_BEETLE_PART9 = 15,
  GFX_MODEL_BIG_BEETLE_PART10 =16,
  GFX_MODEL_COUNT = 17,
} GfxModelIndex;

typedef enum {
  GFX_TEXTURE_TV_BIG = 0,
  GFX_TEXTURE_TV = 1,
  GFX_TEXTURE_BUG_SHIP = 2,
  GFX_TEXTURE_EARTH = 3,
  GFX_TEXTURE_MOON = 4,
  GFX_TEXTURE_MAGGOT = 5,
  GFX_TEXTURE_SATELLITE = 6,
  GFX_TEXTURE_BEETLE1 = 7,
  GFX_TEXTURE_BEETLE2 = 8,
  GFX_TEXTURE_BEETLE3 = 9,
  GFX_TEXTURE_BIG_BEETLE = 10,
  GFX_TEXTURE_COUNT = 11,
} GfxTextureIndex;

#endif
