#ifndef CHANNEL_HIJACK_GFX_INDICES_H
#define CHANNEL_HIJACK_GFX_INDICES_H

typedef enum {
  GFX_MODEL_BUG_SHIP = 0,
  GFX_MODEL_SPHERE = 1,
  GFX_MODEL_MAGGOT = 2,
  GFX_MODEL_SATELLITE = 3,
  GFX_MODEL_BEETLE1 = 4,
  GFX_MODEL_BEETLE2 = 5,
  GFX_MODEL_BEETLE3 = 6,
  GFX_MODEL_COUNT = 7,
} GfxModelIndex;

typedef enum {
  GFX_TEXTURE_TV_BIG = 0,
  GFX_TEXTURE_TV = 1,
  GFX_TEXTURE_BUG_SHIP = 2,
  GFX_TEXTURE_EARTH = 3,
  GFX_TEXTURE_MOON = 4,
  GFX_TEXTURE_MAGGOT = 5,
  GFX_TEXTURE_SATELLITE = 6,
  GFX_TEXTURE_BEETLE1 = 7,
  GFX_TEXTURE_BEETLE2 = 8,
  GFX_TEXTURE_BEETLE3 = 9,
  GFX_TEXTURE_COUNT = 10,
} GfxTextureIndex;

#endif
