param(
    [ValidateSet("Pico", "Windows")]
    [string]$Platform
)

$ErrorActionPreference = "Stop"

if ([string]::IsNullOrWhiteSpace($Platform)) {
    Write-Host "Wybierz platforme docelowa:"
    Write-Host "  1. Raspberry Pi Pico"
    Write-Host "  2. Windows"
    $selection = Read-Host "Platforma [1/2]"

    $Platform = switch ($selection.Trim()) {
        "1" { "Pico" }
        "2" { "Windows" }
        default { throw "Nieprawidlowy wybor '$selection'. Wybierz 1 albo 2." }
    }
}

$repositoryRoot = (Resolve-Path -LiteralPath (Split-Path -Parent $PSScriptRoot)).Path
$cmakeListsPath = Join-Path $repositoryRoot "CMakeLists.txt"

$commonHeader = @'
# This file is generated by tools/select_platform.ps1. Do not edit it directly.
cmake_minimum_required(VERSION 3.13)

set(CMAKE_C_STANDARD 11)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

option(DEBUG_MODE "Show metrics on the display" OFF)
'@

$picoHeader = @'

set(CHANNELHIJACK_PLATFORM "PICO")

# Keep these declarations explicit for the Raspberry Pi Pico VS Code extension.
if(WIN32)
    set(USERHOME $ENV{USERPROFILE})
else()
    set(USERHOME $ENV{HOME})
endif()
set(sdkVersion 2.2.0)
set(toolchainVersion 14_2_Rel1)
set(picotoolVersion 2.2.0)
set(PICO_EXTRAS_FETCH_FROM_GIT ON)
set(picoVscode ${USERHOME}/.pico-sdk/cmake/pico-vscode.cmake)
if(EXISTS ${picoVscode})
    include(${picoVscode})
endif()

set(PICO_BOARD pico2 CACHE STRING "Board type")
include(pico_sdk_import.cmake)
include(pico_extras_import.cmake)

project(ChannelHijackDemo C CXX ASM)
pico_sdk_init()
'@

$windowsHeader = @'

set(CHANNELHIJACK_PLATFORM "WINDOWS")

project(ChannelHijackDemo C CXX)

include(FetchContent)
set(SDL_TEST_LIBRARY OFF CACHE BOOL "" FORCE)
set(SDL_TESTS OFF CACHE BOOL "" FORCE)
set(SDL_EXAMPLES OFF CACHE BOOL "" FORCE)
set(SDL_SHARED ON CACHE BOOL "" FORCE)
set(SDL_STATIC OFF CACHE BOOL "" FORCE)
if(CMAKE_VERSION VERSION_GREATER_EQUAL "3.24")
    FetchContent_Declare(
        SDL3
        GIT_REPOSITORY https://github.com/libsdl-org/SDL.git
        GIT_TAG main
        OVERRIDE_FIND_PACKAGE
    )
else()
    FetchContent_Declare(
        SDL3
        GIT_REPOSITORY https://github.com/libsdl-org/SDL.git
        GIT_TAG main
    )
endif()
FetchContent_MakeAvailable(SDL3)
if(CMAKE_VERSION VERSION_GREATER_EQUAL "3.24")
    unset(SDL3_DIR CACHE)
elseif(EXISTS "${sdl3_BINARY_DIR}/SDL3Config.cmake")
    set(SDL3_DIR "${sdl3_BINARY_DIR}" CACHE PATH "Path to SDL3Config.cmake" FORCE)
    list(PREPEND CMAKE_PREFIX_PATH "${sdl3_BINARY_DIR}")
endif()
'@

$commonProject = @'

include(FetchContent)

# Configuration passed to the Euzebia3D dependency.
set(EUZEBIA3D_PLATFORM "${CHANNELHIJACK_PLATFORM}" CACHE STRING "Target platform for Euzebia3D" FORCE)
set(EUZEBIA3D_USE_PSRAM ON CACHE BOOL "Enable optional PSRAM-backed const asset copies")
set(EUZEBIA3D_TEXTURE_CACHE_ENABLED ON CACHE BOOL "Enable renderer texture cache")
set(EUZEBIA3D_TEXTURE_CACHE_FROM_FLASH OFF CACHE BOOL "Allow texture cache for flash/XIP textures")
set(EUZEBIA3D_TEXTURE_CACHE_FROM_PSRAM ON CACHE BOOL "Allow texture cache for PSRAM/XIP textures")
set(EUZEBIA3D_BUILD_APP OFF CACHE BOOL "" FORCE)

FetchContent_Declare(
    Euzebia3D
    GIT_REPOSITORY https://github.com/yami-five/Euzebia3D.git
    GIT_TAG v0.11.8
)
FetchContent_MakeAvailable(Euzebia3D)

# Use the assets belonging to ChannelHijackDemo instead of dependency defaults.
if(TARGET Euzebia3D_Storage)
    set(CHANNELHIJACK_STORAGE_DIR "${CMAKE_CURRENT_LIST_DIR}/storage")
    set_property(TARGET Euzebia3D_Storage PROPERTY SOURCES "${CHANNELHIJACK_STORAGE_DIR}/storage.c")
    target_include_directories(Euzebia3D_Storage PUBLIC "${CHANNELHIJACK_STORAGE_DIR}")
endif()

add_executable(ChannelHijackDemo
    ChannelHijackDemo.c
    libs/animation/animation.c
    libs/model_animation/model_animation.c
    libs/demo_context/demo_context.c
    libs/demo_context/scenes/scene_1_tv_off.c
    libs/demo_context/scenes/scene_2_program_in.c
    libs/demo_context/scenes/scene_3_program_out.c
    libs/demo_context/scenes/scene_4_weather_in.c
    libs/demo_context/scenes/scene_5_weather_out.c
    libs/demo_context/scenes/scene_6_news_in.c
    libs/demo_context/scenes/scene_7_news_out.c
    libs/demo_context/scenes/scene_8_hijacking_in.c
    libs/demo_context/scenes/scene_9_hijacking_out.c
    libs/demo_context/scenes/scene_10_alert_in.c
    libs/demo_context/scenes/scene_11_alert_out.c
    libs/demo_context/scenes/scene_12_space.c
    libs/demo_context/scenes/scene_12_subscenes/scene_12_subscene1.c
    libs/demo_context/scenes/scene_12_subscenes/scene_12_subscene2.c
    libs/demo_context/scenes/scene_12_subscenes/scene_12_subscene3.c
    libs/demo_context/scenes/scene_12_subscenes/scene_12_subscene4.c
    libs/demo_context/scenes/scene_12_subscenes/scene_12_subscene5.c
    libs/demo_context/scenes/scene_12_subscenes/scene_12_subscene6.c
    libs/grid/grid.c
    libs/sdl_wrapper/sdl_wrapper.c
)
target_include_directories(ChannelHijackDemo PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}"
    "${CMAKE_CURRENT_LIST_DIR}/libs/animation"
    "${CMAKE_CURRENT_LIST_DIR}/libs/model_animation"
    "${CMAKE_CURRENT_LIST_DIR}/libs/demo_context"
    "${CMAKE_CURRENT_LIST_DIR}/libs/grid"
    "${CMAKE_CURRENT_LIST_DIR}/libs/sdl_wrapper"
)
target_link_libraries(ChannelHijackDemo PRIVATE Euzebia3D_libs)

if(DEBUG_MODE)
    target_compile_definitions(ChannelHijackDemo PRIVATE EUZEBIA3D_DEBUG_MODE=1)
endif()
'@

$picoTarget = @'

target_compile_definitions(ChannelHijackDemo PRIVATE PLATFORM_PICO=1)
pico_set_program_name(ChannelHijackDemo "ChannelHijackDemo")
pico_set_program_version(ChannelHijackDemo "0.1")
pico_generate_pio_header(ChannelHijackDemo ${CMAKE_CURRENT_LIST_DIR}/blink.pio)
pico_enable_stdio_uart(ChannelHijackDemo 1)
pico_enable_stdio_usb(ChannelHijackDemo 0)
target_link_libraries(ChannelHijackDemo PRIVATE
    pico_stdlib
    hardware_spi
    hardware_i2c
    hardware_dma
    hardware_pio
    hardware_interp
)
pico_add_extra_outputs(ChannelHijackDemo)
'@

$windowsTarget = @'

target_compile_definitions(ChannelHijackDemo PRIVATE PLATFORM_WINDOWS=1)
'@

$platformHeader, $platformTarget = switch ($Platform) {
    "Pico" { $picoHeader, $picoTarget }
    "Windows" { $windowsHeader, $windowsTarget }
}

$content = @(
    $commonHeader.TrimEnd()
    $platformHeader.TrimEnd()
    $commonProject.TrimEnd()
    $platformTarget.TrimEnd()
) -join [Environment]::NewLine
$content += [Environment]::NewLine

[System.IO.File]::WriteAllText($cmakeListsPath, $content, [System.Text.UTF8Encoding]::new($false))

Write-Host "Aktywna platforma: $Platform"
Write-Host "Wygenerowano: $cmakeListsPath"
