static const ModelAnimationValue maggot_anim_values[] = {
    {0.0195964f, 0.0f, -1.0f, 0.0f},
    {0.0097982f, 0.0f, -1.0f, 0.0f},
    {0.0f, 0.0f, -1.0f, 0.0f},
    {0.0097982f, 0.0f, 1.0f, 0.0f},
    {0.0195964f, 0.0f, 1.0f, 0.0f},
    {0.0097982f, 0.0f, 1.0f, 0.0f},
    {0.0f, 0.0f, 1.0f, 0.0f},
    {0.0097982f, 0.0f, -1.0f, 0.0f},
};

static const ModelAnimation maggot_anim = {
    .values = maggot_anim_values,
    .values_count = 8u,
};